spring.application.name=backend

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/messfinder
spring.datasource.username=postgres
spring.datasource.password=yash5553
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

## Cloudinary (fill later)
#cloudinary.cloud-name=
#cloudinary.api-key=
#cloudinary.api-secret=

# JWT (fill later)
jwt.secret=messfinder-super-secret-key-change-this-later
jwt.expiration=86400000
